receivers:
  otlp:
    protocols:
      http: 
        endpoint: otel:4318
      grpc:
        endpoint: otel:4317

exporters:
  debug:
    verbosity: normal

  otlp/elastic:
    endpoint: 172.19.0.1:31200
    headers:
      # Elastic APM Server secret token
      Authorization: "Bearer 1234"  
    tls:
      insecure: true
  otlphttp/p1:
    #endpoint: 172.17.0.1:32090
    endpoint: http://172.19.0.1:32090/api/v1/otlp
    tls:
      insecure: true
  otlp/p2:
    endpoint: 172.19.0.1:32317
    tls:
      insecure: true
  otlphttp/p3:
    endpoint: http://172.19.0.1:32000/otlp
    tls:
      insecure: true

processors:
  batch:
  transform/t1:
    error_mode: ignore
    trace_statements:
        - set(span.attributes["sku"], Concat(["#", span.attributes["local_sku"]], "")  ) where span.attributes["local_sku"] != nil
        - delete_key(span.attributes, "local_sku") 





extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform/t1]
      exporters: [otlp/elastic, otlp/p2]

    metrics:
      receivers: [otlp]
      processors: []
      exporters: [ otlp/elastic, otlphttp/p1]

    logs:
      receivers: [otlp]
      processors: []
      exporters: [otlp/elastic, otlphttp/p3]

