receivers:
  otlp:
    protocols:
      http: 
        endpoint: otel:4318
      grpc:
        endpoint: otel:4317

exporters:
  logging:
    loglevel: info
  otlp/tempo:
    endpoint: 192.168.8.2:24317
    tls:
      insecure: true
  otlp/elastic:
    endpoint: 192.168.8.2:31200
    headers:
      # Elastic APM Server secret token
      Authorization: "Bearer 1234"  
    tls:
      insecure: true

processors:
  batch:
  metricstransform:
    transforms:
    - include: jvm.memory.used
      action: insert
      new_name: system.memory.actual.free
    - include: jvm.memory.used
      action: insert
      new_name: system.memory.total
    - include: system.cpu.usage
      action: insert
      new_name: system.cpu.total.norm.pct
    - include: system.cpu.usage
      action: insert
      new_name: system.process.cpu.total.norm.pct

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, otlp/elastic]

    metrics:
      receivers: [otlp]
      processors: [metricstransform]
      exporters: [otlp/elastic]
