{
 "title": "Observability",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application Name", "query": { "query": "label_values(job)" } },
   { "name": "log_keyword", "label": "Log Query" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({\"http.server.request.duration_seconds_count\",job=~\"$app_name\", \"http.route\"!=\"/actuator/prometheus\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(\"http.request.method\",\"http.route\") ({\"http.server.request.duration_seconds_count\",job=~\"$app_name\", \"http.route\"!=\"/actuator/prometheus\"})",
     "legendFormat": "{{http.request.method}}{{http.route}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(\"http.request.method\", \"http.route\") ({\"http.server.request.duration_seconds_sum\", job=~\"$app_name\"}) / sum by(\"http.request.method\", \"http.route\") ({\"http.server.request.duration_seconds_count\", job=~\"$app_name\"})",
     "legendFormat": "{{\"http.request.method\"}} {{\"http.route\"}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({\"http.server.request.duration_seconds_count\",job=~\"$app_name\", \"http.response.status_code\"=~\"5.*\"})"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum  ({\"http.server.request.duration_seconds_count\",job=~\"$app_name\", \"http.response.status_code\"=~\"2.*\", \"http.route\"!=\"/actuator/prometheus\"}) / sum  ({\"http.server.request.duration_seconds_count\", job=~\"$app_name\", \"http.route\"!=\"/actuator/prometheus\"})",
     "legendFormat": "{{http.route}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum ({\"http.server.request.duration_seconds_count\",job=~\"$app_name\", \"http.response.status_code\"=~\"5.*\", \"http.route\"!=\"/actuator/prometheus\"}) / sum ({\"http.server.request.duration_seconds_count\",job=~\"$app_name\", \"http.route\"!=\"/actuator/prometheus\"})",
     "legendFormat": "{{http.route}}"
    }
   ]
  },
  {
   "title": "Log of All Apps",
   "type": "logs",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"code.*\"} | logfmt"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(\"http.route\")(rate({\"http.server.request.duration_seconds_count\",job=~\"$app_name\"}[2m]))",
     "legendFormat": "{{http.route}}"
    }
   ]
  }
 ]
}